#+Title: Run Virtual Labs on Virtual Box
#+Date: 24-10-2017
#+Author: VLEAD 

* Overview and Motivation

  Virtual Labs is providing an approach to access Labs and
  its experiments using [[https://www.virtualbox.org/wiki][VirtualBox]]. 

  This approach eliminates the need of installing dependencies
  such as Adobe Flash, Java3D, etc. on user machine
 
  The VirtualBox that is provided by Virtual Labs can be
  used for both [[https://info.vlabs.ac.in/workshops/][Online]] and [[https://info.vlabs.ac.in/college-cloud-edition/][Offline( College Cloud)]] versions
  of Virtual Labs.

* Audience
  Virtual Lab users.

* Systems Requirements
  Minimum systems requirements.
  1. Operating Systems ( OS )- Any OS that supports Oracle
     VirtualBox or VMWare Workstation. The machine should
     have [[https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Virtualization_Administration_Guide/sect-Virtualization-Troubleshooting-Enabling_Intel_VT_and_AMD_V_virtualization_hardware_extensions_in_BIOS.html][provision to support Virtualization]] Technology
  2. 4GB RAM.
  3. Dual Core processor.

* VirtualBox installation steps
  1. Visit the [[https://www.virtualbox.org/wiki/Downloads][VirtualBox]] provider website. Please note that
     installation needs to be done only once.
  2. Choose the appropriate VirtualBox version based on the Operating
     System ( OS ) installed on the machine.
  3. Download the selected VirtualBox.
  4. VirtualBox installation steps on *Windows OS*.
     1. Double click on *.exe* file.
     2. Follow the instructions appearing on installation wizard.
     3. After installation, ensure that a VirtualBox icon is created
        on the desktop.
  5. Steps 6 and 7 are installation step examples for CentOS-6.x and
     Ubuntu 14.04.  These installation steps will vary based on the
     version of the OS installed on the user machine.  Please follow
     the [[https://www.virtualbox.org/wiki/Linux_Downloads][link]] for appropriate steps.
  6. VirtualBox installation steps on *CentOS-6.X OS*.
     - Download RPM package.
       #+BEGIN_EXAMPLE
       wget http://download.virtualbox.org/virtualbox/5.1.6/VirtualBox-5.1-5.1.6_110634_el6-1.x86_64.rpm
       #+END_EXAMPLE
     - Install VirtualBox.
       #+BEGIN_EXAMPLE
       sudo rpm -i VirtualBox-5.1-5.1.6_110634_el6-1.x86_64.rpm
       #+END_EXAMPLE
  7. VirtualBox installation steps on *Ubuntu 14.04*.
     - Download VirtualBox.
       #+BEGIN_EXAMPLE
       wget http://download.virtualbox.org/virtualbox/5.2.0/virtualbox-5.2_5.2.0-118431~Ubuntu~trusty_amd64.deb
       #+END_EXAMPLE
     - Install VirtualBox.
       #+BEGIN_EXAMPLE
       sudo dpkg -i virtualbox-5.2_5.2.0-118431~Ubuntu~trusty_amd64.deb
       #+END_EXAMPLE
  8. VirtualBox installation steps on *Mac OS X*
     - Download the VirtualBox from [[http://download.virtualbox.org/virtualbox/5.2.0/VirtualBox-5.2.0-118431-OSX.dmg][here]] and Save it.
     - Double click on downloaded file =.dmg=.
     - Follow the instructions and install it.
* Virtual-Labs VirtualBox import steps  
  1. Follow the [[http://files.virtual-labs.ac.in/downloads/virtual-boxes/][link]] to download and save the
     *ubuntu-14.04-college-cloud.ova*. Please note that import steps
     need to be done only once.
  2. Double click on the *ubuntu-14.04-college-cloud.ova* file.
  3. A import window will appear.
  4. Import the file *ubuntu-14.04-college-cloud.ova* and follow the
     steps to install it. This may take 5 to 10  minutes.
  5. On completion of step 4, select the *ubuntu-14.04-college-cloud*
     from the VirtualBox window. Please allocate the =Processor= and
     =Memory/RAM= size from the Settings menu appropriately based on
     the system configuration of the user machine.
     
     - *NOTE :: Recommended Settings for the imported box*
       #+BEGIN_EXAMPLE
       Processor --> 1
       Memory/RAM size --> 2GB
       #+END_EXAMPLE
